/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package wooga.gradle

import spock.lang.Specification
import wooga.gradle.Library

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
